name: Check and Preview DNS changes

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dns-update'
    paths:
      - 'dnsconfig.js'



jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check DNS configuration
        uses: dan-is-not-the-man/dnscontrol-action@v4.7.3-beta.1
        with:
          args: check

  preview:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3
      - name: Preview DNS changes
        id: preview
        uses: dan-is-not-the-man/dnscontrol-action@v4.7.3-beta.1
        env:
          DESEC_API_TOKEN: ${{ secrets.DESEC_API_TOKEN }}
        with:
          args: preview
      - name: Comment diff on PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.preview.outputs.output }}
            ```
          check_for_duplicate_msg: true
