name: Push DNS changes

on:
  push:
    branches:
      - main
    paths:
      - 'dnsconfig.js'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push DNS changes
        uses: dan-is-not-the-man/dnscontrol-action@v4.7.3-beta.1
        env:
          DESEC_API_TOKEN: ${{ secrets.DESEC_API_TOKEN }}
        with:
          args: push
